### ISSUE TITLE
Update AutoMerger mapping for the created release branch

### ISSUE THREAD

**Issue by vaibhavjainwiz** [opendatahub-io/modelmesh-serving#133]
Modelmesh enabled the auto merger for a release branch. If the new release branch is ready to promote for RHODS, you should update [source_mapping.yaml file](https://github.com/red-hat-data-services/rhods-devops-infra/blob/main/src/config/source_map.yaml) to pint to the branch.

Ex)
```
- name: rest-proxy
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/rest-proxy.git
    branch: release-v0.10.0   <-----
  dest:
    url: https://github.com/red-hat-data-services/rest-proxy.git
    branch: main
```
